name: Update Fixtures Calendar

on:
  schedule:
    - cron: '0 6 * * *'  # Runs at 6am UTC / 7am UK time
  workflow_dispatch:      # Allow manual runs too

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps

      - name: Run scraper
        run: python scrape_fixtures.py

      - name: Generate ICS
        run: python generate_ics.py

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add fixtures.json maryhill-fixtures.ics
          git commit -m "🔄 Auto-update fixtures and calendar" || echo "No changes to commit"
          git push
